apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: session-cleaner
            image: jomanocob/django_app:latest
            envFrom:
              - configMapRef:
                  name: django-config
            imagePullPolicy: Never
            command:
            - /bin/sh
            - -c
            - python manage.py clearsessions
          restartPolicy: OnFailure
          ttlSecondsAfterFinished: 20
          startingDeadlineSeconds: 100
